#Overrides all other config options for easy difficulty management
#This value is changed by the in-game config. It does nothing otherwise.
#Range: 0 ~ 4
Difficulty = 4

["Details about how the player is affected by temperature"]
	#Defines the minimum habitable temperature
	#Range: -Infinity ~ Infinity
	"Minimum Habitable Temperature" = 0.5785714285796939
	#Defines the maximum habitable temperature
	#Range: -Infinity ~ Infinity
	"Maximum Habitable Temperature" = 1.7142857143102042
	#Rate at which the player's body temperature changes (default: 1.0 (100%))
	#Range: 0.0 ~ Infinity
	"Rate Multiplier" = 1.2
	#Damage dealt to the player when they are too hot or too cold
	#Range: 0.0 ~ Infinity
	"Temperature Damage" = 2.0

["Item settings"]
	#Allow fire resistance to block overheating damage
	"Fire Resistance Immunity" = true
	#Allow ice resistance to block freezing damage
	"Ice Resistance Immunity" = true
	#Thermometer item is required to see detailed world temperature
	"Require Thermometer" = false

["Misc temperature-related things"]
	#Sets whether damage scales with difficulty
	"Damage Scaling" = true
	#When set to true, players cannot sleep if they are cold or hot enough to die
	"Prevent Sleep When in Danger" = true

["Temperature Effects"]

	["Temperature Effects".Hot]
		#When set to true, the player's view distance will decrease when they are too hot
		"Heatstroke Fog" = true

	["Temperature Effects".Cold]
		#When set to true, some of the player's hearts will freeze when they are too cold, preventing regeneration
		"Freezing Hearts" = true
		#When set to true, the player's attack knockback will be reduced when they are too cold
		"Cold Knockback Reduction" = true
		#When set to true, the player's movement speed will be reduced when they are too cold
		"Cold Slowness" = true
		#When set to true, the player's mining speed will be reduced when they are too cold
		"Cold Mining Fatigue" = true

["Grace Period Details"]
	#The number of ticks after the player spawns during which they are immune to temperature effects
	#Range: > 0
	"Grace Period Length" = 6000
	#Enables the grace period
	"Grace Period Enabled" = true

[Hearth]
	#How strong the hearth is
	#Range: 0.0 ~ 1.0
	"Hearth Strength" = 0.5
	#List of additional blocks that the hearth can spread through
	#Use this list if the hearth isn't spreading through particular blocks that it should
	"Hearth Spread Whitelist" = ["minecraft:iron_bars", "minecraft:jungle_leaves", "minecraft:oak_leaves", "minecraft:spruce_leaves", "minecraft:dark_oak_leaves", "minecraft:acacia_leaves", "minecraft:birch_leaves", "minecraft:azalea_leaves", "minecraft:flowering_azalea_leaves", "minecraft:mangrove_leaves", "minecraft:cherry_leaves", "eldritch_end:primordial_leaves", "vinery:cherry_leaves", "vinery:apple_leaves", "vinery:grapevine_leaves", "undergarden:smogstem_leaves", "undergarden:wigglewood_leaves", "undergarden:grongle_leaves", "alexscaves:ancient_leaves", "forbidden_arcanus:aurum_leaves", "forbidden_arcanus:nuggety_aurum_leaves", "occultism:otherworld_leaves", "occultism:otherworld_leaves_natural", "betternether:anchor_tree_leaves", "betternether:nether_sakura_leaves", "betternether:rubeus_leaves", "betternether:willow_leaves", "betterend:amaranita_fur", "betterend:blue_vine_fur", "betterend:cave_bush", "betterend:dragon_tree_leaves", "betterend:glowing_pillar_leaves", "betterend:helix_tree_leaves", "betterend:lacugrove_leaves", "betterend:lucernia_leaves", "betterend:lucernia_outer_leaves", "betterend:mossy_glowshroom_fur", "betterend:pythadendron_leaves", "betterend:tenanea_leaves", "betterend:tenanea_outer_leaves", "betterend:umbrella_tree_membrane"]
	#List of additional blocks that the hearth cannot spread through
	#Use this list if the hearth is spreading through particular blocks that it shouldn't
	"Hearth Spread Blacklist" = []

["Cold Soul Fire"]
	#Converts damage dealt by Soul Fire to cold damage (default: true)
	#Does not affect the block's temperature
	"Cold Soul Fire" = true

