
[light_sources]
	water_sensitive_check = true
	block_entities = true
	entities = true
	self = true

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				zombie_horse = true
				panda = true
				axolotl = true
				bee = true
				arrow = true
				cow = true
				magma_cube = true
				pig = true
				allay = true
				skeleton = true
				llama = true
				bat = true
				husk = true
				frog = true
				hoglin = true
				rabbit = true
				silverfish = true
				firework_rocket = true
				armor_stand = true
				drowned = true
				experience_orb = true
				dolphin = true
				item = true
				stray = true
				shulker = true
				turtle = true
				salmon = true
				wandering_trader = true
				wither_skeleton = true
				goat = true
				ocelot = true
				item_frame = true
				vindicator = true
				horse = true
				phantom = true
				minecart = true
				ender_dragon = true
				llama_spit = true
				glow_squid = true
				glow_item_frame = true
				squid = true
				parrot = true
				creeper = true
				lightning_bolt = true
				enderman = true
				chicken = true
				trader_llama = true
				donkey = true
				chest_minecart = true
				tropical_fish = true
				fox = true
				slime = true
				pillager = true
				iron_golem = true
				zombified_piglin = true
				piglin = true
				blaze = true
				cat = true
				zombie = true
				ender_pearl = true
				sheep = true
				player = true
				pufferfish = true
				potion = true
				trident = true
				villager = true
				wolf = true
				skeleton_horse = true
				tnt_minecart = true
				zombie_villager = true
				polar_bear = true
				strider = true
				hopper_minecart = true
				cave_spider = true
				witch = true
				cod = true
				spider = true

			[light_sources.settings.entities.alexscaves]
				teletor = true
				gammaroach = true
				quarry_smasher = true
				boundroid_winch = true
				gloomoth = true
				nucleeper = true
				radgill = true
				underzealot = true
				brainiac = true
				boundroid = true
				magnetic_weapon = true
				notor = true
				magnetron = true
				vesper = true
				corrodent = true
				ferrouslime = true
				raycat = true

			[light_sources.settings.entities.spectre]
				spectre_phantom = true
				murk_lurker = true
				spectre = true
				parasitic_maggot_succesful = true
				viggo_and_felix_aggro = true
				creep = true
				creep_runner = true
				parasitic_maggot = true
				viggoand_felix = true

			[light_sources.settings.entities.alexsmobs]
				murmur_head = true
				kangaroo = true
				gelada_monkey = true
				skelewag = true
				blue_jay = true
				bone_serpent_part = true
				cachalot_echo = true
				catfish = true
				anteater = true
				tasmanian_devil = true
				centipede_tail = true
				cosmic_cod = true
				rhinoceros = true
				comb_jelly = true
				endergrade = true
				jerboa = true
				skunk = true
				roadrunner = true
				rattlesnake = true
				leafcutter_ant = true
				shoebill = true
				blobfish = true
				lobster = true
				mimicube = true
				grizzly_bear = true
				snow_leopard = true
				potoo = true
				moose = true
				tiger = true
				rocky_roller = true
				centipede_head = true
				flutter = true
				orca = true
				maned_wolf = true
				crow = true
				banana_slug = true
				elephant = true
				crocodile = true
				crimson_mosquito = true
				spectre = true
				anaconda = true
				hammerhead_shark = true
				seal = true
				sunbird = true
				emu = true
				triops = true
				mimic_octopus = true
				gazelle = true
				tarantula_hawk = true
				soul_vulture = true
				tusklin = true
				underminer = true
				anaconda_part = true
				enderiophage = true
				terrapin = true
				gorilla = true
				flying_fish = true
				platypus = true
				capuchin_monkey = true
				cockroach = true
				murmur = true
				komodo_dragon = true
				bone_serpent = true
				bald_eagle = true
				centipede_body = true
				seagull = true
				mantis_shrimp = true
				raccoon = true
				fly = true
				toucan = true
				alligator_snapping_turtle = true
				giant_squid = true
				cachalot_whale = true
				hummingbird = true
				bison = true
				frilled_shark = true
				sugar_glider = true

			[light_sources.settings.entities.forbidden_arcanus]
				crimson_lightning_bolt = true
				lost_soul = true

			[light_sources.settings.entities.ytech]
				deer = true

			[light_sources.settings.entities.botania]
				mana_burst = true
				babylon_weapon = true

			[light_sources.settings.entities.naturalist]
				rattlesnake = true
				deer = true
				snail = true
				rhino = true
				firefly = true
				bluejay = true
				snake = true
				coral_snake = true
				cardinal = true
				catfish = true
				boar = true
				robin = true
				bass = true
				tortoise = true
				butterfly = true
				sparrow = true
				elephant = true

			[light_sources.settings.entities.majruszsdifficulty]
				illusioner = true
				cursed_armor = true
				tank = true
				creeperling = true

			[light_sources.settings.entities.graveyard]
				acolyte = true
				nameless_hanged = true
				revenant = true
				corrupted_vindicator = true
				skeleton_creeper = true
				corrupted_pillager = true
				ghoul = true
				reaper = true
				nightmare = true

			[light_sources.settings.entities.born_in_chaos_v1]
				pumpkin_spirit = true
				firelight = true
				zombie_fisherman = true
				decaying_zombie = true
				fallen_chaos_knight = true
				dark_vortex = true
				supreme_bonescaller_stage_2 = true
				glutton_fish = true
				skeleton_thrasher = true
				corpse_fish = true
				zombie_bruiser = true
				shy_spirit = true
				baby_skeleton_2 = true
				spirit_guide = true
				bonescaller_not_despawn = true
				dread_hound_not_despawn = true
				bloody_gadfly = true
				zombie_clown = true
				thornshell_crab = true
				door_knight = true
				diamond_termite = true
				projectile_staffof_magic_arrows_2 = true
				maggot = true
				door_knight_not_despawn = true
				seared_spirit = true
				skeleton_demoman = true
				decrepit_skeleton = true
				wither_scuttler = true
				firelight_not_despawn = true
				nightmare_stalker = true
				spirit_guide_assistant = true
				dread_hound = true
				decaying_zombie_not_despawn = true
				baby_skeleton = true
				swarmer = true
				barrel_zombie = true
				restless_spirit = true
				bonescaller = true
				phantom_creeper = true
				dire_hound_leader = true
				supreme_bonescaller = true
				baby_skeleton_minion = true
				bone_imp_minion = true
				zombie_clown_not_despawn = true
				phantom_creeper_copy = true
				corpse_fly = true
				skeleton_thrasher_not_despawn = true

			[light_sources.settings.entities.adventurez]
				deer = true
				orc = true
				amethyst_golem = true
				enderwarthog = true
				void_shadow = true
				ender_whale = true
				summoner = true

			[light_sources.settings.entities.cataclysm]
				lionfish = true
				koboleton = true
				deepling = true
				wall_watcher = true
				flame_strike = true
				ender_golem = true
				endermaptera = true
				screen_shake = true
				deepling_angler = true
				the_watcher = true
				coral_spear = true
				void_rune = true
				deepling_brute = true
				the_harbinger = true
				ender_guardian = true
				the_prowler = true

			[light_sources.settings.entities.create]
				stationary_contraption = true
				contraption = true
				super_glue = true

			[light_sources.settings.entities.meadow]
				brown_bear = true
				wooly_cow = true
				water_buffalo = true

			[light_sources.settings.entities.eldritch_end]
				dendler = true

			[light_sources.settings.entities.untamedwilds]
				rhino = true
				arowana = true
				whale_shark = true
				snake = true
				baleen_whale = true
				catfish = true
				spitter = true
				boar = true
				tortoise = true
				hyena = true
				camel = true
				bear = true
				terror_bird = true
				spadefish = true
				giant_salamander = true
				shark = true
				triggerfish = true
				opossum = true
				manatee = true
				hippo = true
				large_snake = true
				newt = true
				softshell_turtle = true
				monitor = true
				tarantula = true
				football_fish = true
				sawfish = true
				big_cat = true
				trevally = true
				sunfish = true
				giant_clam = true
				king_crab = true
				wildebeest = true
				spit = true
				bison = true

			[light_sources.settings.entities.weather2]
				lightning_bolt = true

			[light_sources.settings.entities.vinery]
				mule = true
				wandering_winemaker = true

			[light_sources.settings.entities.embers]
				ancient_golem = true

			[light_sources.settings.entities.railways]
				conductor = true

			[light_sources.settings.entities.bosses_of_mass_destruction]
				spore_ball = true
				lich = true
				obsidilith = true
				petal_blade = true
				charged_ender_pearl = true
				gauntlet = true
				soul_star = true
				void_blossom = true

			[light_sources.settings.entities.cold_sweat]
				chameleon = true

			[light_sources.settings.entities.enhancedai]
				fishing_hook = true

			[light_sources.settings.entities.aquamirae]
				maw = true
				tortured_soul = true
				anglerfish = true
				golden_moth = true
				pillagers_patrol = true
				spinefish = true

			[light_sources.settings.entities.sanitydim]
				rotting_stalker = true

