
[general]
	#If mod can change behaviour of specified blocks to require valid tool for harvesting
	makeBlocksRequireValidTool = true
	#List of blocks that will require valid tool for harvesting
	makeBlocksRequireValidToolList = ["minecraft:acacia_log", "minecraft:acacia_wood", "minecraft:birch_log", "minecraft:birch_wood", "minecraft:cherry_log", "minecraft:cherry_wood", "minecraft:jungle_log", "minecraft:jungle_wood", "minecraft:oak_log", "minecraft:oak_wood", "minecraft:dark_oak_log", "minecraft:dark_oak_wood", "minecraft:mangrove_log", "minecraft:mangrove_wood", "minecraft:spruce_log", "minecraft:spruce_wood", "minecraft:stripped_acacia_log", "minecraft:stripped_acacia_wood", "minecraft:stripped_birch_log", "minecraft:stripped_birch_wood", "minecraft:stripped_cherry_log", "minecraft:stripped_cherry_wood", "minecraft:stripped_jungle_log", "minecraft:stripped_jungle_wood", "minecraft:stripped_oak_log", "minecraft:stripped_oak_wood", "minecraft:stripped_dark_oak_log", "minecraft:stripped_dark_oak_wood", "minecraft:stripped_mangrove_log", "minecraft:stripped_mangrove_wood", "minecraft:stripped_spruce_log", "minecraft:stripped_spruce_wood", "minecraft:dirt", "minecraft:dirt_path", "minecraft:grass_block", "minecraft:farmland", "minecraft:podzol", "minecraft:mycelium", "minecraft:coarse_dirt", "minecraft:rooted_dirt"]
	#Enables crafting Sharp Flint by right-clicking on stone
	craftSharpFlintByRightClickingOnStone = true

[dryingRack]
	#If Drying Rack should stop working during rain
	noDryingDuringRain = true
	#List of biome tags, where will be drying 2x slower
	slowDryingBiomeTags = ["forge:is_wet"]
	#List of biome tags, where will be drying 2x faster
	fastDryingBiomeTags = ["forge:is_dry"]

[irrigation]

	[irrigation.aqueduct]
		#Base amount of fluid stored per block
		#Range: > 1
		baseFluidStoragePerBlock = 500
		#If raining should fill aqueduct
		rainingFillAqueduct = true
		#Amount of which will be aqueduct filled per nth tick when raining
		#Range: > 1
		rainingFillAmount = 1
		#How often should be filled aqueduct when raining (1 - every tick, 20 - every second)
		#Range: > 1
		rainingFillPerNthTick = 10
		#If aqueduct must see sky and must be in valid biome where is raining when raining for filling
		validBlockForRaining = true

	[irrigation.valve]
		#Amount of which will be aqueduct filled every nth tick thru valve
		#Range: > 1
		valveFillAmount = 1
		#How often should be filled aqueduct thru valve (1 - every tick, 20 - every second)
		#Range: > 1
		valveFillPerNthTick = 10

	[irrigation.hydrator]
		#Amount of which will be aqueduct drained every nth tick thru hydrator
		#Range: > 1
		hydratorDrainAmount = 100
		#How often should be drained aqueduct thru hydrator (1 - every tick, 20 - every second)
		#Range: > 1
		hydratorDrainPerNthTick = 200

	[irrigation.fertilizer]
		#How long last single piece of fertilizer
		#Range: > 1
		fertilizerDuration = 600
		#How often should be applied bone meal effect (1 / n chance per tick)
		#Range: > 1
		applyFertilizerChance = 60

